"""
Simulate quasar continuum and emission lines using `simqso` without any absorber templates.

This script generates synthetic quasar spectra with random properties.
The power-law slopes of the continuum model are varied using a gaussian distribution
of the slopes:
    GaussianSampler(-1.7, 0.1) and GaussianSampler(-0.3, 0.2)
with a break at 1215 Å.

The luminosities are randomly generated by sampling a random black hole mass
and a random Eddington ratio from log-normal distributions:
    M_BH : GaussianSampler(8.67, 0.5)
    R_Edd = GaussianSampler(-0.83, 0.4)

The rest-frame luminosity density at 1450Å is then calculated by assuming
a bolometric correction of 5 (Richards et al. 2006).

Fe lines are included using a re-scaled template of the Vestergaard & Wilkes (2001)
template. Lastly, broad lines are included following the Baldwin effect.

Optional broad absorption line (BAL) features can be added if requested.

The script generates a list of template input parameters in the output directory
with the following parameters:
    ID: quasar model id
    z: quasar redshift
    absMag: absolute magnitude (at 1450Å)
    smcDustEBV: E(B-V) in mag following the SMC extinction curve
    LOG_MBH: log of black hole mass in units of M_sun
    LOG_REDD: log of Eddington ratio
"""

from astropy.cosmology import Planck13
from astropy.table import Table, vstack
from astropy.io import fits
import numpy as np
from scipy import stats
import os
import glob
import gc
import pickle
import pandas as pd

from simqso.sqgrids import *
from simqso import sqbase
from simqso.sqrun import buildSpectraBulk, buildQsoSpectrum
from tqdm import tqdm

from fits_utils import *

# ------------------------------------------------------------------------------------------------------------

__author__ = 'Jens-Kristian Krogager, modified by Nicolas Guerra-Varas'


here = os.path.abspath(os.path.dirname(__file__))

def simulate_quasars(nqso=None, expand_factor=1.0, z_list=None, names_list=None, z_range=(1.0, 4.5), 
                     wavelen_grid='/data2/home2/nguerrav/TNG50_spec/npy_files/TNG50_wavelength_grid_extended.npy', wave_range=(3000, 11000), 
                     dust_mode='exponential', #BAL=False, 
                     output_dir='/data2/home2/nguerrav/QSO_simpaqs/QSO_simpaqs/golden_sample_expanded/QSO_templates', 
                     aparent_mags=None, aparent_mag_errs=None, fobs=None, subsurveys=None):
    """
    Simulate a set of quasars without any absorber templates.
    
    Parameters
    ----------
    nqso : int
        Number of quasars to simulate
    expand_factor : float, optional
        factor by which to increase the sample size given
    z_list : array-like, optional
        List of specific redshifts to use for the quasars. If provided, nqso is set to len(z_list)
    names_list : array-like, optional
        List of names corresponding to each quasar
    z_range : tuple
        Redshift range (min, max) to sample from
    wave_range : tuple
        Wavelength range in Angstroms
    dust_mode : str
        Dust sampling mode: 'exponential' or 'uniform'
    BAL : bool
        Whether to include broad absorption line features
    output_dir : str
        Output directory for the simulated quasar spectra
    
    Returns
    -------
    subset : astropy.table.Table
        Table with quasar parameters
    """

    if not os.path.exists(output_dir):
        os.makedirs(output_dir)

    if wavelen_grid is not None:
        wave = np.load(wavelen_grid)
    else:
        wave = np.arange(wave_range[0], wave_range[1], 0.1)
        # TNG wavelength grid here

    if z_list is not None:
        z_all = np.array(z_list)
        nqso = len(z_all)
        print(f"Using {nqso} provided redshifts")
    else:
        z_all = np.random.uniform(z_range[0], z_range[1], nqso)

    if expand_factor > 1.0:
        z_all = np.repeat(z_all, int(expand_factor))
        aparent_mags = np.repeat(aparent_mags, int(expand_factor))
        aparent_mag_errs = np.repeat(aparent_mag_errs, int(expand_factor))
        fobs = np.repeat(fobs, int(expand_factor))
        subsurveys = np.repeat(subsurveys, int(expand_factor))
        if names_list is not None:
            names_list = np.repeat(names_list, int(expand_factor))
        nqso = len(z_all)
        print(f"Expanded to {nqso} quasars with expand_factor={expand_factor}")

    # Sampling MBH and LEdd from Rakshit, Stalin & Kotilainen (2020)
    logM_BH = np.random.normal(8.67, 0.5, nqso)
    logR_Edd = np.random.normal(-0.83, 0.4, nqso)
    logL_bol = np.log10(3.2e4) + logM_BH + logR_Edd
    BC = 5.  # Richards et al. (2006)
    M_all = 4.8 - 2.5*logL_bol + 2.5*np.log10(BC)

    M = AbsMagVar(FixedSampler(M_all), restWave=1450)
    z = RedshiftVar(FixedSampler(z_all))
    
    # Include dust sampled from E(B-V)
    if dust_mode.lower() == 'exponential':
        # based roughly on Krawczyk et al. 2015
        Ebv_all = stats.expon.rvs(loc=0., scale=0.05, size=nqso)
    else:
        Ebv_all = stats.uniform.rvs(0., 0.5, size=nqso)
    dust = SMCDustVar(FixedSampler(Ebv_all))

    qsos = QsoSimPoints([M, z, dust], cosmo=Planck13, units='luminosity')

    # use the canonical values for power law continuum slopes in FUV/NUV, with breakpoint at 1215A
    contVar = BrokenPowerLawContinuumVar([
        GaussianSampler(-1.7, 0.1),  # slope before break
        GaussianSampler(-0.3, 0.2)],  # slope after break
        [1215.]  # breakpoint is fixed --> GaussianSampler(1215., 5.)?
        )

    # generate lines using the Baldwin Effect emission line model from BOSS DR9
    emLineVar = generateBEffEmissionLines(qsos.absMag)  # lines listed in /home/nguerrav/4MOST_like_data/simqso/simqso/data
                                                        # for each line: wavelength, logEW, logWidth
    # print('emLineVar:', emLineVar()[0][0], '\n')

    # the default iron template from Vestergaard & Wilkes 2001 was modified to fit BOSS spectra
    fescales = [(0, 1540, 0.5),
                (1540, 1680, 2.0),
                (1680, 1868, 1.6),
                (1868, 2140, 1.0),
                (2140, 3500, 1.0)]
    feVar = FeTemplateVar(VW01FeTemplateGrid(qsos.z, wave, scales=fescales))
    # Default velocity broadening = 5000 km/s FWHM

    # Now add the features to the QSO grid
    qsos.addVars([contVar, emLineVar, feVar])

    # print('qsos.data before: \n', qsos.data)

    # ready to generate spectra
    meta, spectra = buildSpectraBulk(wave, qsos, saveSpectra=True)
    print('len(spectra) =', len(spectra))

    print("Creating quasar models:")

    # Save the templates:
    all_ids = []
    # all_bal_types = []
    dnum = len(glob.glob(f'{output_dir}/QSOs_*.fits')) + 1
    for num, spec in enumerate(tqdm(spectra)):
        z_str = str(np.round(z_all[num], 4))#.replace('.', '_')

        if names_list is not None:
            target_name = names_list[num]
            model_id = f'QSO_sim_z{z_str}_{target_name}'
        else:
            model_id = f'QSO_z{z_str}_{num+dnum:06}'

        filename = f'{output_dir}/{model_id}.fits'
        all_ids.append(model_id)

        hdu = fits.HDUList()
        hdr = fits.Header()
        hdr['AUTHOR'] = 'NGGV'
        hdr['COMMENT'] = 'Synthetic quasar model based on simqso'
        hdr['REDSHIFT_ESTIMATE'] = z_all[num]
        hdr['MAG'] = (M_all[num], "Abs. magnitude 1450")
        hdr['EBV'] = (Ebv_all[num], "Mag")
        hdr['LOG_MBH'] = (logM_BH[num], "log(M_BH / Msun)")
        hdr['LOG_REDD'] = (logR_Edd[num], "log(R_Edd)")
        hdr['LOG_LBOL'] = (logL_bol[num], 'log(Lbol)')
        hdr['ID'] = model_id
        prim = fits.PrimaryHDU(header=hdr)
        hdu.append(prim)
        col_wl = fits.Column(name='LAMBDA', array=wave, format='1D', unit='Angstrom')
        col_flux = fits.Column(name='FLUX_DENSITY', array=spec, format='1E', unit='erg/(s cm**2 Angstrom)')
        tab = fits.BinTableHDU.from_columns([col_wl, col_flux])
        tab.name = 'TEMPLATE'
        hdu.append(tab)
        hdu.writeto(filename, overwrite=True, output_verify='silentfix')

    qsos.data['TEMPLATE'] = np.array(all_ids, dtype='<U50')
    qsos.data['redshift'] = z_all
    qsos.data['log_Mbh'] = logM_BH
    qsos.data['log_REdd'] = logR_Edd
    qsos.data['log_Lbol'] = logL_bol
    qsos.data['abs_qso_mag'] = M_all
    qsos.data['EBV'] = Ebv_all
    qsos.data['MAG'] = aparent_mags
    qsos.data['MAG_ERR'] = aparent_mag_errs
    qsos.data['fobs'] = fobs
    qsos.data['SUBSURVEY'] = np.array(subsurveys, dtype='<U20') if subsurveys is not None else None

    if names_list is not None:
        qsos.data['NAME'] = names_list
    
    if os.path.exists(f'{output_dir}/golden_sample_expanded.fits'):
        qsos_prev = Table.read(f'{output_dir}/golden_sample_expanded.fits')
        qsos = vstack([qsos_prev, qsos.data])
    else:
        qsos = qsos.data
    qsos.write(f'{output_dir}/golden_sample_expanded.fits', overwrite=True)
    qsos.write('/data2/home2/nguerrav/Catalogues/golden_sample_expanded.fits', overwrite=True)

def main():
    from argparse import ArgumentParser
    parser = ArgumentParser('Simulate quasars without absorber templates')
    parser.add_argument('--input_cat_path', type=str, default='data2/home2/nguerrav/Catalogues/ByCycle_Final_Cat_fobs_qso_templates_with_SNR_golden_label_QSO_props.fits')
    parser.add_argument("--number", type=int, default=None,
                        help="Number of quasars to simulate [default=100]")
    parser.add_argument("--zlist", type=str, default=None,
                        help="File containing list of redshifts to use (one per line)")
    parser.add_argument("--wavelen_grid", type=str, default='/data2/home2/nguerrav/TNG50_spec/npy_files/TNG50_wavelength_grid_extended.npy',
                        help="File with wavelength grid over which to simulate the QSOs")
    # parser.add_argument("--zmin", type=float, default=1.0,
    #                     help="Minimum redshift [default=1.0]")
    # parser.add_argument("--zmax", type=float, default=4.5,
    #                     help="Maximum redshift [default=4.5]")
    parser.add_argument("--wmin", type=float, default=3000,
                        help="Minimum wavelength in Angstrom [default=3000]")
    parser.add_argument("--wmax", type=float, default=11000,
                        help="Maximum wavelength in Angstrom [default=11000]")
    parser.add_argument('--dust', type=str, default='exponential',
                        help="Dust sampling mode: 'exponential' or 'uniform' [default=exponential]")
    parser.add_argument('--expanding_factor', type=int, default=None)
    parser.add_argument("--dir", type=str, 
                        default='./QSO_templates/', 
                        help="Output directory")

    args = parser.parse_args()
    
    print(f"Wavelength range: {args.wmin} - {args.wmax} Å")
    print(f"Dust mode: {args.dust}")
    print(f"Output directory: {args.dir}")

    cat = pandas_from_fits(args.input_cat_path)
    # cat = cat.loc[cat['golden']]
    # print(f'Golden sample original size: {cat.shape[0]}')

    if args.number is not None:
        nqsos = args.number
    else:
        nqsos = cat.shape[0]
    
    if args.expanding_factor is not None:
        expanding_factor = args.expanding_factor
    else:
        expanding_factor = 1.0

    print(f"Total number of quasars to simulate: {nqsos*expanding_factor}")

    if nqsos*expanding_factor > 50000:
        # Process in chunks to manage memory
        chunk_size = int(np.ceil(10000 / expanding_factor))
        num_chunks = (nqsos + chunk_size - 1) // chunk_size
        
        for chunk_idx in range(num_chunks):
            start_idx = chunk_idx * chunk_size
            end_idx = min((chunk_idx + 1) * chunk_size, nqsos)
            
            print(f"\nProcessing chunk {chunk_idx+1}/{num_chunks} (QSOs {start_idx+1}-{end_idx})")
            
            chunk_cat = cat.iloc[start_idx:end_idx]
            z_arr = chunk_cat.REDSHIFT_ESTIMATE.values
            # names = chunk_cat['NAME'].to_numpy(dtype=str)
            mags_apparent = chunk_cat.MAG.values
            mags_err_apparent = chunk_cat.MAG_ERR.values
            fobs = chunk_cat.fobs.values
            subsurveys = chunk_cat.SUBSURVEY.values
            
            simulate_quasars(
                nqso=len(z_arr),
                expand_factor=expanding_factor, 
                z_list=z_arr, 
                # names_list=names,
                wave_range=(args.wmin, args.wmax),
                dust_mode=args.dust,
                output_dir=args.dir, 
                aparent_mags=mags_apparent, 
                aparent_mag_errs=mags_err_apparent, 
                fobs=fobs, 
                subsurveys=subsurveys
                )
            
            # del chunk_cat, z_arr, names
            del chunk_cat, z_arr
            gc.collect()

    else:
        z_arr = cat.REDSHIFT_ESTIMATE.values
        names = cat['NAME'].to_numpy(dtype=str)
        mags_apparent = cat.MAG.values
        mags_err_apparent = cat.MAG_ERR.values
        fobs = cat.fobs.values
        subsurveys = cat.SUBSURVEY.values

        simulate_quasars(
            nqso=len(z_arr),
            expand_factor=expanding_factor, 
            # z_range=(args.zmin, args.zmax),
            z_list=z_arr, 
            # names_list=names,
            wave_range=(args.wmin, args.wmax),
            dust_mode=args.dust,
            # BAL=args.bal,
            output_dir=args.dir, 
            aparent_mags=mags_apparent, 
            aparent_mag_errs=mags_err_apparent, 
            fobs=fobs, 
            subsurveys=subsurveys
        )

    # update each QSOs TEMPLATE column to the newly created template
    model_params = Table.read(f'{args.dir}/model_parameters.fits')
    model_params = model_params['NAME', 'ID'].to_pandas()
    model_params['ID'] = model_params['ID'].astype(pd.StringDtype())
    model_params['NAME'] = model_params['NAME'].astype(pd.StringDtype())
    qso_name_to_id = dict(zip(model_params['NAME'], model_params['ID'] + '.fits'))
    cat['TEMPLATE'] = cat['NAME'].map(qso_name_to_id)

    save_to_fits(cat, args.output_dir, 'ByCycle_Final_Cat_fobs_qso_templates.fits')

if __name__ == '__main__':
    main()
